workflows:
  default-workflow:
    name: Build 4K App (Android & iOS)
    max_build_duration: 40
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - flutter clean
      - flutter pub get
      - flutter analyze
      - flutter test
      - flutter build apk --release
      - flutter build ios --release --no-codesign

    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
